# Generated by Django 4.0 on 2022-04-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='tracking_id',
            field=models.IntegerField(),
        ),
    ]
