# Generated by Django 4.0 on 2022-04-12 14:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
        ('parcel_management', '0002_alter_parcel_tracking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='routing.branch')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel', to='parcel_management.parcel')),
            ],
        ),
    ]
