# Generated by Django 4.0 on 2022-04-15 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
        ('parcel_management', '0003_pathhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='current_branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='current_branch', to='routing.branch'),
            preserve_default=False,
        ),
    ]
